### ISSUE TITLE
Include TypeScript def & Exclude test files from distribution

### ISSUE THREAD

**Issue by gotham8x** [borderless/web-jwt#1]
## Include TypeScript def

You already have TS def, but you didn't put the declaration in `package.json`. As a result, I'm encountering the error `Cannot find module '@borderless/web-jwt' or its corresponding type declarations.ts(2307)`.

Add the following field to the `package.json` and it should resolve the issue. I just wonder how could you miss it. Have you tested your package by trying installing it?

```yml
// ...
"types": "dist/index.d.ts",
// ...
```

## Exclude test files from distribution

Can you just exclude unnecessary test files from distribution? This will significantly reduce the package size.

![image](https://github.com/borderless/web-jwt/assets/83201216/ccfd8d93-2ca8-4ce6-b1cb-9c704cff6b4e)

**Comment by blakeembrey** [comment]
> I just wonder how could you miss it. Have you tested your package by trying installing it?

Yes, it works correctly. This is an ESM package, and `types` is included in the exports definition. What version of TypeScript are you using and do you have ESM enabled?

**Comment by blakeembrey** [comment]
There’s some documentation here if you’d like to learn more: https://www.typescriptlang.org/docs/handbook/esm-node.html#packagejson-exports-imports-and-self-referencing

And FWIW, TypeScript would already have been looking relative to the `main` if that exists so the `types` is redundant in that case.

**Comment by gotham8x** [comment]
ESM is not new. I have been working with it for years up until now.

I am using the latest TypeScript 5.x.

Never mind, I ended up using another package.

**Comment by blakeembrey** [comment]
I’m aware it’s not new. Top level `main` and `types` is for a CommonJS package. Are you sure you’re actually using ES modules?

To use ESM resolution in TypeScript you need to set `module: Node16` or `module: NodeNext`. It’s in the link I shared above. Otherwise you’re just relying on the standard CommonJS module resolution in TypeScript.

**Comment by blakeembrey** [comment]
Do you have a reproduction I can look at where this isn’t working? Can you share your `tsconfig.json`? I’ve been using this for months in other TypeScript projects and it works fine if you’re using ESM.

**Comment by blakeembrey** [comment]
Separately, I removed the spec files from the package in https://github.com/borderless/web-jwt/commit/b2944f536bf89efc68290ae2ba6cca5ff646f27b.

**Comment by blakeembrey** [comment]
> ESM is not new. I have been working with it for years up until now.

Also wanted to just flag this, but you probably haven't been using ESM _with TypeScript_ for years since it only just got official support last year: https://devblogs.microsoft.com/typescript/announcing-typescript-4-7/#ecmascript-module-support-in-node-js

I can't tell what you're referring to without seeing your project, but it may be that you've been transpiling or bundling? Tools like Webpack/ESBuild/etc. tend to cover up the ugliness of official ESM in node.
